import turtle
sun = turtle.Turtle()
jin = turtle.Turtle()
shui = turtle.Turtle()
di = turtle.Turtle()
huo = turtle.Turtle()
mu = turtle.Turtle()
tu = turtle.Turtle()
sun.color("yellow")
sun.dot(20)
jin.up()
jin.color("blue")
jin.forward(100)
jin.left(90)
jin.down()
jin.circle(100,390)
jin.dot(20)
shui.color("green")
shui.up()
shui.forward(120)
shui.left(90)
shui.down()
shui.circle(120,200)
shui.dot(20)
di.color('red')
di.up()
di.fd(150)
di.left(90)
di.down()
di.circle(180,90)
di.dot(20)
huo.color("black")
huo.up()
huo.fd(200)
huo.left(90)
huo.down()
huo.circle(180,90)
huo.dot(20)
mu.color("orange")
mu.up()
mu.forward(220)
mu.left(100)
mu.down()
mu.circle(120,80)
mu.dot(20)
tu.color("light blue")
tu.up()
tu.forward(250)
tu.left(90)
tu.down()
tu.circle(180,60)
tu.dot(20)
